version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      TZ: America/Sao_Paulo
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - springboot-networks

  santt4na-api-rest:
    build: .
    image: santt4na/santt4na-api-rest
    restart: always
    working_dir: /santt4na-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql:3306/mydb?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: user
      SPRING.DATASOURCE.PASSWORD: pass
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - springboot-networks

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - springboot-networks

volumes:
  dbdata:
  portainer_data:

networks:
  springboot-networks:
    driver: bridge